name = "EconDatasets"                                                                                  
uuid = "562f5c66-7e5e-4212-a941-c5eaf01f4968"                                                                      
version = "0.1.0"
