name = "EconDatasets"                                                                                  
uuid = "7781f4xx-0ba3-5c4a-a982-d971b817e3xx"                                                                      
version = "0.1.0"
