name = "EconDatasets"                                                                                  
uuid = "7781f4ab-0ba3-5c4a-a982-d971b817e312"                                                                      
version = "0.1.0"
